server:
  port: ${port:8080}

application:
  base-package: com.suixingpay.transaction
spring:
  application:
    name: transaction-demo
  datasource:
    druid:
      url: jdbc:mysql://172.16.60.247:3306/transaction_demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
      username: fd
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis:  3000000 # 连接保持50分钟，单位是毫秒,因为公司防火墙长连接保持最长时间为1小时；此参数一定要结合实际情况进行配置。
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /* #配置被filter作用的url


mybatis:
  # 如果Mapper.java和Mapper.xml在同一个包下，可以不用设置
  #  mapperLocations: classpath:com.suixingpay.transaction.mapper/*.xml
  typeAliasesPackage: ${application.base-package}.domain
  configuration:
    cacheEnabled: false
    # 一定要设置，避免个别SQL执行时间过长，把系统搞跨
    default-statement-timeout: 5